//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.13 at 02:13:31 PM PST 
//


package com.loftus.contacts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contact", propOrder = {
    "firstname",
    "lastname",
    "address",
    "address2",
    "city",
    "stateOfResidence",
    "zip",
    "phone",
    "email",
    "notes"
})
public class Contact {

    protected String firstname;
	protected String lastname;
	protected String address;
	protected String address2;
	protected String city;
    protected String stateOfResidence;
    protected String zip;
    protected String phone;
    protected String email;
    protected String notes;
    @XmlAttribute(name = "id", required = true)
    protected int id;
    
    public String getFirstname() {
    	return firstname;
    }
    
    public void setFirstname(String value) {
    	this.firstname = value;
    }
    
    public String getLastname() {
        return lastname;
    }

    public void setLastname(String value) {
        this.lastname = value;
    }

    public String getAddress() {
    	return this.address;
    }
    
    public void setAddress(String value) {
    	this.address = value;
    }
    
    public String getAddress2() {
    	return this.address2;
    }
    
    public void setAddress2(String value) {
    	this.address2 = value;
    }
    
    public String getCity() {
    	return this.city;
    }
    
    public void setCity(String value) {
    	this.city = value;
    }
    
    public String getStateOfResidence() {
        return stateOfResidence;
    }

    public void setStateOfResidence(String value) {
        this.stateOfResidence = value;
    }
    
    public String getZip() {
    	return zip;
    }
    
    public void setZip(String value) {
    	this.zip = value;
    }
    
    public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public int getId() {
        return id;
    }

    public void setId(int value) {
        this.id = value;
    }

}
