//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.13 at 02:13:31 PM PST 
//


package com.loftus.contacts.data.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.loftus.contacts.Contact;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contactList", propOrder = {
    "contact"
})
public class ContactList {

    @XmlElement(required = true)
    protected List<Contact> contact;

    public List<Contact> getContacts() {
        if (contact == null) {
            contact = new ArrayList<Contact>();
        }
        return this.contact;
    }
    
    public void setContacts(List<Contact> contactList) {
    	this.contact = contactList;
    }

}
