//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.13 at 02:13:31 PM PST 
//


package com.loftus.contacts.data.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.loftus.contacts.*;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.loftus.contacts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ContactStore_QNAME = new QName("", "contactStore");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.loftus.contacts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContactList }
     * 
     */
    public ContactList createContactList() {
        return new ContactList();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contactStore")
    public static JAXBElement<ContactList> createContactStore(ContactList value) {
        return new JAXBElement<ContactList>(_ContactStore_QNAME, ContactList.class, null, value);
    }

}
